### ISSUE TITLE
can this  pix4 use fuel planner? any example?

### ISSUE THREAD

**Issue by FPSychotic** [HKUST-Aerial-Robotics/NxtPX4#1]
hi, looks great but it looks your actual fuel,fast planner use DJI FCUs, any example of them with your nxtpix4?

thanks

**Comment by Peize-Liu** [comment]
Sorry for the late reply. Theoretically, it can be used for fast-planner. I suggest you refer to FAST-lab's repo for further support with fast-planner running with px4

**Comment by FPSychotic** [comment]
Thanks , very kind wish you the better
